export const API_PREFIX = '/api/v5';

export const api = {
  login: `${API_PREFIX}/login`,
  userInfo: `${API_PREFIX}/getUserInfo`,
  bookshelf: `${API_PREFIX}/getBookshelf`,
  bookshelfPage: `${API_PREFIX}/getBookshelfPage`,
  bookInfo: `${API_PREFIX}/getBookinfo`,
  chapterList: `${API_PREFIX}/getChapterListNew`,
  bookContent: `${API_PREFIX}/getBookContentNew`,
  search: `${API_PREFIX}/searchBook`,
  saveProgress: `${API_PREFIX}/saveBookProgress`,
  saveBook: `${API_PREFIX}/saveBook`,
  refreshBook: `${API_PREFIX}/refreshBook`,
  bookSources: `${API_PREFIX}/getBookSourcesNew`,
  bookSourcesPage: `${API_PREFIX}/getBookSourcesPage`,
  rssSources: `${API_PREFIX}/getRssSourcessNew`,
  rssSourcesPage: `${API_PREFIX}/getRssSourcessPage`,
  ttsSources: `${API_PREFIX}/getallttsNew`,
  ttsSourcesPage: `${API_PREFIX}/getallttsPage`,
  stopBookSource: `${API_PREFIX}/stopbookSource`,
  delBookSource: `${API_PREFIX}/delbookSource`,
  saveBookSources: `${API_PREFIX}/saveBookSources`,
  stopRssSource: `${API_PREFIX}/stopRssSource`,
  delRssSource: `${API_PREFIX}/delRssSource`,
  saveRssSources: `${API_PREFIX}/saveRssSources`,
  addTts: `${API_PREFIX}/addtts`,
  delTts: `${API_PREFIX}/deltts`,
};
